#!/usr/bin/env python3
"""Build data/runtime_patch.jsonl for CN (or any) clients.

Uses FrontierTextHandler to extract live pointer-slot offsets from a game
directory, then maps Mogapedia EN targets by xpath+index onto those slots.

Example:
  py -3 scripts/build_runtime_patch.py ^
      --game-dir "D:\\MHFZ-CN\\client\\pc\\dat" ^
      --translations data/translations-en.json ^
      --out data/runtime_patch.jsonl

Addresses are file-relative offsets (hex). The mod's optional offset-map
path expects absolute process addresses — convert offline with
--image-base if you know the in-memory load address, or leave relative and
use the live headers apply path instead.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TH = ROOT / "third_party" / "FrontierTextHandler"
sys.path.insert(0, str(TH))

FILE_MAP = {
    "dat": "mhfdat.bin",
    "pac": "mhfpac.bin",
    "inf": "mhfinf.bin",
    "jmp": "mhfjmp.bin",
    "gao": "mhfgao.bin",
    "sqd": "mhfsqd.bin",
    "rcc": "mhfrcc.bin",
    "msx": "mhfmsx.bin",
    "mfd": "mhfmfd.bin",
}


def load_en(path: Path) -> dict[str, dict[int, str]]:
    doc = json.loads(path.read_text(encoding="utf-8"))
    root = doc.get("en") or doc.get("translations") or doc
    out: dict[str, dict[int, str]] = {}
    if not isinstance(root, dict):
        raise SystemExit("unexpected translations shape")
    for xpath, rows in root.items():
        if xpath in ("metadata", "meta") or not isinstance(rows, list):
            continue
        bucket: dict[int, str] = {}
        for row in rows:
            if not isinstance(row, dict):
                continue
            idx = row.get("index")
            target = row.get("target") or ""
            if idx is None or not target:
                continue
            bucket[int(idx)] = target
        if bucket:
            out[xpath] = bucket
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--game-dir", type=Path, required=True)
    ap.add_argument("--translations", type=Path, required=True)
    ap.add_argument("--out", type=Path, default=ROOT / "data" / "runtime_patch.jsonl")
    ap.add_argument("--image-base", type=lambda s: int(s, 0), default=0,
                    help="If set, emit absolute addresses (base + file offset)")
    ap.add_argument("--game-version", default="zz")
    args = ap.parse_args()

    from src.common import load_file_data, read_extraction_config  # type: ignore
    from src.pointer_tables import extract_text_data_from_bytes  # type: ignore

    en = load_en(args.translations)
    args.out.parent.mkdir(parents=True, exist_ok=True)

    written = 0
    with args.out.open("w", encoding="utf-8") as out:
        out.write("# Generated by scripts/build_runtime_patch.py\n")
        for xpath, rows in sorted(en.items()):
            try:
                node = read_extraction_config(xpath)
            except Exception as ex:
                print(f"skip (no headers): {xpath} ({ex})")
                continue
            file_key = xpath.split("/")[0]
            bin_name = FILE_MAP.get(file_key)
            if not bin_name:
                print(f"skip (unknown file): {xpath}")
                continue
            bin_path = args.game_dir / bin_name
            if not bin_path.exists():
                # allow game-dir = client/pc with dat/ subfolder
                alt = args.game_dir / "dat" / bin_name
                if alt.exists():
                    bin_path = alt
                else:
                    print(f"skip (missing bin): {bin_path}")
                    continue
            data = load_file_data(str(bin_path))
            try:
                entries = extract_text_data_from_bytes(data, node, args.game_version)
            except Exception as ex:
                print(f"skip (extract failed) {xpath}: {ex}")
                continue
            import struct
            for index, target in rows.items():
                if index < 0 or index >= len(entries):
                    continue
                entry = entries[index]
                subs = entry.get("sub_offsets") or [entry["offset"]]
                parts_txt = target.split("{j}")
                if len(parts_txt) != len(subs):
                    if not (len(parts_txt) == 1 and len(subs) == 1):
                        continue
                for slot_off, part in zip(subs, parts_txt):
                    ptr = struct.unpack_from("<I", data, int(slot_off))[0]
                    str_addr = ptr + int(args.image_base)
                    end = ptr
                    while end < len(data) and data[end] != 0:
                        end += 1
                    row = {
                        "address": hex(str_addr),
                        "target": part,
                        "xpath": xpath,
                        "index": index,
                        "slot": hex(int(slot_off) + int(args.image_base)),
                        "max": max(1, end - ptr),
                    }
                    out.write(json.dumps(row, ensure_ascii=False) + "\n")
                    written += 1
            print(f"{xpath}: mapped against {len(entries)} live entries")
    print(f"Wrote {written} patches → {args.out}")
    return 0 if written else 1


if __name__ == "__main__":
    raise SystemExit(main())
